### ISSUE TITLE
Info of 600

### ISSUE THREAD

**Issue by wasif1** [Xtha-Sunil/Numbers#851]

**Comment by Xtha-Sunil** [comment]
Hi @wasif1, thanks for opening this issue!

**Comment by Xtha-Sunil** [comment]
Happy Contribution! 🎉

**Comment by Xtha-Sunil** [comment]
Please make pr with pr-message "Closes #[issue number]"
Eg `Closes #851`
It closes the issue on merge.
Thank You.
